# Generated by Django 5.2.1 on 2025-12-17 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Download timestamp"
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True, help_text="Device information", max_length=255
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of downloader", null=True
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Downloaded game",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who downloaded (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="download_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Download History",
                "verbose_name_plural": "Download Histories",
                "ordering": ["-timestamp"],
            },
        ),
    ]
