import { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.name': 'IndieHub',
    'nav.home': 'Home',
    'nav.games': 'Games',
    'nav.library': 'My Library',
    'nav.dashboard': 'Games Management',
    'nav.admin': 'Game Status',
    'nav.categoryManagement': 'Category Management',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'home.title': 'Discover Independent Games',
    'home.subtitle': 'Supporting developers from underrepresented communities',
    'home.featured': 'Featured Game',
    'home.popular': 'Most Popular',
    'home.newReleases': 'New Releases',
    'game.download': 'Download',
    'game.addToLibrary': 'Add to Library',
    'game.removeFromLibrary': 'Remove from Library',
    'game.reviews': 'Reviews',
    'game.writeReview': 'Write a Review',
    'game.categories': 'Categories',
    'game.status': 'Status',
    'game.developer': 'Developer',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.username': 'Username',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.role': 'Role',
    'auth.role.user': 'User',
    'auth.role.developer': 'Developer',
    'dashboard.submitGame': 'Submit New Game',
    'dashboard.myGames': 'Games',
    'dashboard.pending': 'Pending',
    'dashboard.approved': 'Approved',
    'dashboard.rejected': 'Rejected',
    'gameForm.title': 'Title',
    'gameForm.description': 'Description',
    'gameForm.file': 'Game File',
    'gameForm.categories': 'Select Categories',
    'search.placeholder': 'Search games...',
    'filter.categories': 'Filter by Category',
    'library.empty': 'Your library is empty',
    'library.addGames': 'Add games to your library to access them quickly',
    'notFound.sector': 'SECTOR NOT FOUND',
    'notFound.coordinates': 'System failure: Coordinates invalid...',
    'notFound.void': "The neural link has been severed. You've wandered into the digital void.",
    'notFound.return': 'INITIATE RETURN SEQUENCE',
    'common.loading': 'LOADING...',
    'common.cancel': 'CANCEL',
    'common.view': 'VIEW',
    'common.edit': 'EDIT',
    'common.delete': 'DELETE',
    'common.update': 'UPDATE',
    'common.submit': 'SUBMIT',
    'common.confirm': 'CONFIRM',
    'common.save': 'SAVE',
    'common.all': 'ALL',
    'common.status.pending': 'PENDING',
    'common.status.approved': 'APPROVED',
    'common.status.rejected': 'REJECTED',
    'dashboard.editGame': 'EDIT GAME',
    'dashboard.analytics': 'ANALYTICS',
    'dashboard.noGames': 'NO GAMES SUBMITTED YET',
    'dashboard.deleteConfirm': 'DELETE THIS GAME?',
    'dashboard.screenshots': 'SCREENSHOTS',
    'dashboard.manageScreenshots': 'MANAGE EXISTING SCREENSHOTS',
    'dashboard.coverImage': 'COVER IMAGE',
    'dashboard.bannerImage': 'BANNER IMAGE',
    'dashboard.gameFile': 'GAME FILE',
    'dashboard.leaveEmpty': 'LEAVE EMPTY TO KEEP CURRENT FILE',
    'dashboard.downloadsDaily': 'Downloads (daily)',
    'dashboard.ratingDaily': 'Average rating (daily)',
    'dashboard.ratingDistribution': 'Rating distribution',
    'dashboard.noData': 'No data available',
    'admin.panel': 'ADMIN PANEL',
    'admin.rejectionReason': 'REJECTION REASON',
    'admin.provideReason': 'PLEASE PROVIDE A REJECTION REASON',
    'admin.approve': 'APPROVE',
    'admin.reject': 'REJECT',
    'admin.confirmReject': 'CONFIRM REJECT',
    'admin.developerId': 'DEVELOPER ID',
    'admin.created': 'CREATED',
    'admin.noGamesFound': 'NO GAMES FOUND',
    'game.playNow': 'PLAY NOW',
    'home.topRated': 'Top Rated',
    'home.trending': 'Trending Now',
    'home.gems': 'Hidden Gems',
    'home.mostPopularDesc': 'Based on downloads',
    'home.newReleasesDesc': 'Recently added games',
    'home.topRatedDesc': 'Best average star rating',
    'home.trendingDesc': 'Fastest growing downloads this week',
    'home.hiddenGemsDesc': 'High rating + low downloads',
    'home.devQuestion': 'ARE YOU A DEVELOPER?',
    'home.devAction': 'PUBLISH YOUR GAMES TO THOUSANDS OF PLAYERS.',
    'home.startToday': 'START TODAY',
    'game.description': 'DESCRIPTION',
    'game.screenshots': 'SCREENSHOTS',
    'game.rating': 'RATING',
    'game.comment': 'COMMENT',
    'game.noReviews': 'NO REVIEWS YET',
    'game.downloading': 'DOWNLOADING...',
    'game.notFound': 'GAME NOT FOUND',
    'common.error': 'AN ERROR OCCURRED',
    'cat.new': 'SUBMIT NEW CATEGORY',
    'cat.edit': 'EDIT CATEGORY',
    'cat.add': 'ADD CATEGORY',
    'cat.nameEn': 'NAME (EN)',
    'cat.nameAr': 'NAME (AR)',
    'cat.descEn': 'DESCRIPTION (EN)',
    'cat.descAr': 'DESCRIPTION (AR)',
    'cat.confirmDelete': 'ARE YOU SURE?',
    'cat.updated': 'CATEGORY UPDATED',
    'cat.created': 'CATEGORY CREATED',
    'cat.failedSave': 'FAILED TO SAVE CATEGORY',
    'cat.failedDelete': 'FAILED TO DELETE CATEGORY',
    'auth.loginFailed': 'LOGIN FAILED. PLEASE TRY AGAIN.',
    'auth.loggingIn': 'LOGGING IN...',
    'auth.noAccount': "DON'T HAVE AN ACCOUNT?",
    'auth.hasAccount': 'ALREADY HAVE AN ACCOUNT?',
    'auth.registering': 'REGISTERING...',
    'auth.passMatch': 'PASSWORDS DO NOT MATCH',
    'auth.passLength': 'PASSWORD MUST BE AT LEAST 8 CHARACTERS',
    'auth.regFailed': 'REGISTRATION FAILED. PLEASE TRY AGAIN.',
    'home.viewAll': 'VIEW ALL',
    'game.viewDetails': 'VIEW DETAILS',
    'library.confirmRemove': 'ARE YOU SURE?',
    'library.removed': 'GAME REMOVED FROM LIBRARY',
    'library.removeFailed': 'FAILED TO REMOVE GAME',
  },
  ar: {
    'app.name': 'إندي هاب',
    'nav.home': 'الرئيسية',
    'nav.games': 'الألعاب',
    'nav.library': 'مكتبتي',
    'nav.dashboard': 'إدارة الألعاب',
    'nav.admin': 'حالة الألعاب',
    'nav.categoryManagement': 'إدارة الفئات',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'التسجيل',
    'nav.logout': 'تسجيل الخروج',
    'home.title': 'اكتشف الألعاب المستقلة',
    'home.subtitle': 'دعم المطورين من المجتمعات الممثلة تمثيلاً ناقصاً',
    'home.featured': 'اللعبة المميزة',
    'home.popular': 'الأكثر شعبية',
    'home.newReleases': 'أحدث الإصدارات',
    'game.download': 'تحميل',
    'game.addToLibrary': 'إضافة إلى المكتبة',
    'game.removeFromLibrary': 'إزالة من المكتبة',
    'game.reviews': 'التقييمات',
    'game.writeReview': 'اكتب تقييماً',
    'game.categories': 'الفئات',
    'game.status': 'الحالة',
    'game.developer': 'المطور',
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'التسجيل',
    'auth.username': 'اسم المستخدم',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.role': 'الدور',
    'auth.role.user': 'مستخدم',
    'auth.role.developer': 'مطور',
    'dashboard.submitGame': 'إرسال لعبة جديدة',
    'dashboard.myGames': 'الألعاب',
    'dashboard.pending': 'قيد الانتظار',
    'dashboard.approved': 'موافق عليه',
    'dashboard.rejected': 'مرفوض',
    'gameForm.title': 'العنوان',
    'gameForm.description': 'الوصف',
    'gameForm.file': 'ملف اللعبة',
    'gameForm.categories': 'اختر الفئات',
    'search.placeholder': 'ابحث عن الألعاب...',
    'filter.categories': 'تصفية حسب الفئة',
    'library.empty': 'مكتبتك فارغة',
    'library.addGames': 'أضف الألعاب إلى مكتبتك للوصول إليها بسرعة',
    'notFound.sector': 'القطاع غير موجود',
    'notFound.coordinates': 'فشل النظام: الإحداثيات غير صالحة...',
    'notFound.void': 'تم قطع الرابط العصبي. لقد تجولت في الفراغ الرقمي.',
    'notFound.return': 'بدء تسلسل العودة',
    'common.loading': 'جاري التحميل...',
    'common.cancel': 'إلغاء',
    'common.view': 'عرض',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.update': 'تحديث',
    'common.submit': 'إرسال',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.all': 'الكل',
    'common.status.pending': 'قيد الانتظار',
    'common.status.approved': 'مقبول',
    'common.status.rejected': 'مرفوض',
    'dashboard.editGame': 'تعديل اللعبة',
    'dashboard.analytics': 'التحليلات',
    'dashboard.noGames': 'لم يتم رفع أي ألعاب بعد',
    'dashboard.deleteConfirm': 'هل أنت متأكد من حذف هذه اللعبة؟',
    'dashboard.screenshots': 'لقطات الشاشة',
    'dashboard.manageScreenshots': 'إدارة لقطات الشاشة الموجودة',
    'dashboard.coverImage': 'صورة الغلاف',
    'dashboard.bannerImage': 'صورة البانر',
    'dashboard.gameFile': 'ملف اللعبة',
    'dashboard.leaveEmpty': 'اتركه فارغاً للاحتفاظ بالملف الحالي',
    'dashboard.downloadsDaily': 'التحميلات (يومياً)',
    'dashboard.ratingDaily': 'متوسط التقييم (يومياً)',
    'dashboard.ratingDistribution': 'توزيع التقييمات',
    'dashboard.noData': 'لا توجد بيانات متاحة',
    'admin.panel': 'لوحة الإدارة',
    'admin.rejectionReason': 'سبب الرفض',
    'admin.provideReason': 'يرجى تقديم سبب للرفض',
    'admin.approve': 'قبول',
    'admin.reject': 'رفض',
    'admin.confirmReject': 'تأكيد الرفض',
    'admin.developerId': 'رقم المطور',
    'admin.created': 'تاريخ الإنشاء',
    'admin.noGamesFound': 'لم يتم العثور على ألعاب',
    'game.playNow': 'العب الآن',
    'home.topRated': 'الأعلى تقييماً',
    'home.trending': 'الرائج الآن',
    'home.gems': 'جواهر خفية',
    'home.mostPopularDesc': 'بناءً على عمليات التنزيل',
    'home.newReleasesDesc': 'الألعاب المضافة حديثاً',
    'home.topRatedDesc': 'أفضل متوسط تقييم بالنجوم',
    'home.trendingDesc': 'الأسرع نمواً في عمليات التنزيل هذا الأسبوع',
    'home.hiddenGemsDesc': 'تقييم عالي + تنزيلات منخفضة',
    'home.devQuestion': 'هل أنت مطور؟',
    'home.devAction': 'انشر ألعابك للآلاف من اللاعبين.',
    'home.startToday': 'ابدأ اليوم',
    'game.description': 'الوصف',
    'game.screenshots': 'لقطات الشاشة',
    'game.rating': 'التقييم',
    'game.comment': 'التعليق',
    'game.noReviews': 'لا توجد تقييمات بعد',
    'game.downloading': 'جاري التحميل...',
    'game.notFound': 'اللعبة غير موجودة',
    'common.error': 'حدث خطأ ما',
    'cat.new': 'إضافة فئة جديدة',
    'cat.edit': 'تعديل الفئة',
    'cat.add': 'إضافة فئة',
    'cat.nameEn': 'الاسم (EN)',
    'cat.nameAr': 'الاسم (AR)',
    'cat.descEn': 'الوصف (EN)',
    'cat.descAr': 'الوصف (AR)',
    'cat.confirmDelete': 'هل أنت متأكد؟',
    'cat.updated': 'تم تحديث الفئة',
    'cat.created': 'تم إنشاء الفئة',
    'cat.failedSave': 'فشل في حفظ الفئة',
    'cat.failedDelete': 'فشل في حذف الفئة',
    'auth.loginFailed': 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
    'auth.loggingIn': 'جاري تسجيل الدخول...',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.registering': 'جاري التسجيل...',
    'auth.passMatch': 'كلمات المرور غير متطابقة',
    'auth.passLength': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    'auth.regFailed': 'فشل التسجيل. يرجى المحاولة مرة أخرى.',
    'home.viewAll': 'عرض الكل',
    'game.viewDetails': 'عرض التفاصيل',
    'library.confirmRemove': 'هل أنت متأكد من الإزالة؟',
    'library.removed': 'تمت إزالة اللعبة من المكتبة',
    'library.removeFailed': 'فشل في إزالة اللعبة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language') as Language;
    return stored || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

